use_frameworks!

platform :ios, '9.0'

target 'MNO_Example' do
  pod 'MNO', :path => '../'

  target 'MNO_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
